FROM golang:alpine

RUN apk update && apk add git

RUN mkdir -p /go/src/github.com/byuoitav
ADD . /go/src/github.com/byuoitav/monster-monitoring-service

WORKDIR /go/src/github.com/byuoitav/monster-monitoring-service
RUN go get -d -v
RUN go install -v

CMD ["/go/bin/monster-monitoring-service"]

EXPOSE 10000
